In [2]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [6]:
#1.) How many negative numbers are there?

len(a[a < 0])

4

In [7]:
#2.) How many positive numbers are there?

len(a[a > 0])

5

In [10]:
#3.) How many even positive numbers are there?

#len(a[(a > 0) & (a % 2 == 0)]) same as size

a[(a > 0) & (a % 2 == 0)].size

3

In [23]:
#4.) If you were to add 3 to each data point, how many positive numbers would there be?

a[(a + 1) & (a > 0)].size

12

In [36]:
a.std()

8.06225774829855

In [41]:
#5.) If you squared each number, what would the new mean and standard deviation be?

(a ** 2).std()  
    

144.0243035046516

In [40]:
(a ** 2).mean()

74.0

In [45]:
#6.)
# A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. Center the data set. 
# See this link for more on centering.

(a - a.mean()).mean()

0.0

In [47]:
#7.) Calculate the z-score for each data point.

n = (a - a.mean())
d = a.std()

n/d

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [50]:
#8.) Copy the setup and exercise directions from More Numpy 
# Practice into your numpy_exercises.py and add your solutions.

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_of_a = sum([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [51]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = min([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

55


In [ ]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

max_of_a = max([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [65]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
import statistics
mean_of_a = statistics.mean(a)

In [67]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
import math

math.prod(a)

3628800

In [70]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

squares_of_a = [i ** 2 for i in a]

In [71]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

odds_in_a = [i for i in a if i % 2 != 0]

In [72]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

evens_in_a = [i for i in a if i % 2 == 0]

In [73]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [76]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

b = np.array ([
    [3, 4, 5],
    [6, 7, 8]
])

sum_of_b = b.sum()

print(sum_of_b)

33


In [81]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 

min_of_b = b.min()



3

In [82]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

max_of_b = b.max()

8

In [83]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

mean_of_b = b.mean()

mean_of_b

5.5

In [84]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

product_of_b = b.prod()

product_of_b

20160

In [86]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

squares_of_b = b ** 2

squares_of_b


array([[ 9, 16, 25],
       [36, 49, 64]])

In [94]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

#step_1 = b % 2
#step_2 = step_1 != 0
#odds_in_b = b[step_2]

odds_in_b = b[b % 2 != 0]


odds_in_b

array([3, 5, 7])

In [95]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

evens_in_b = b[b % 2 == 0]

evens_in_b


array([4, 6, 8])

In [97]:
# Exercise 9 - print out the shape of the array b.

b.shape

TypeError: 'tuple' object is not callable

In [98]:
# Exercise 10 - transpose the array b.

b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

In [99]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [100]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [102]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

c = np.array(c)

In [105]:
# Exercise 1 - Find the min, max, sum, and product of c.

print(c.min())
print(c.max())
print(c.sum())
print(c.prod())

1
9
45
362880


In [107]:
# Exercise 2 - Determine the standard deviation of c.
c.std()

2.581988897471611

In [108]:
# Exercise 3 - Determine the variance of c.
c.var()

6.666666666666667

In [109]:
# Exercise 4 - Print out the shape of the array c
print(c.shape)

(3, 3)


In [110]:
# Exercise 5 - Transpose c and print out transposed result.
print(c.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [112]:
# Exercise 6 - Get the dot product of the array c with c. 
c.prod()

362880

In [114]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
np.sum(c * c.transpose())

261

In [115]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
np.prod((c * c.transpose()))

131681894400

In [106]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d = np.array(d)

In [119]:
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [122]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [126]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [127]:
# Exercise 4 - Find all the negative numbers in d
d[d < 0]

array([-90, -30, -45, -45])

In [128]:
# Exercise 5 - Find all the positive numbers in d
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [129]:
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [130]:
# Exercise 7 - Determine how many unique numbers there are in d.
np.unique(d).size

11

In [131]:
# Exercise 8 - Print out the shape of d.
d.shape

(3, 6)

In [132]:
# Exercise 9 - Transpose and then print out the shape of d.
print((d.transpose()).shape)

(6, 3)


In [134]:
# Exercise 10 - Reshape d into an array of 9 x 2
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])